/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package nr.rrc.definitions;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class CSIReportFramework implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private BerInteger maxNumberPeriodicCSIReportPerBWP = null;
	private BerInteger maxNumberAperiodicCSIReportPerBWP = null;
	private BerInteger maxNumberSemiPersistentCSIReportPerBWP = null;
	private BerInteger simultaneousCSIReportsAllCC = null;
	
	public CSIReportFramework() {
	}

	public CSIReportFramework(byte[] code) {
		this.code = code;
	}

	public void setMaxNumberPeriodicCSIReportPerBWP(BerInteger maxNumberPeriodicCSIReportPerBWP) {
		this.maxNumberPeriodicCSIReportPerBWP = maxNumberPeriodicCSIReportPerBWP;
	}

	public BerInteger getMaxNumberPeriodicCSIReportPerBWP() {
		return maxNumberPeriodicCSIReportPerBWP;
	}

	public void setMaxNumberAperiodicCSIReportPerBWP(BerInteger maxNumberAperiodicCSIReportPerBWP) {
		this.maxNumberAperiodicCSIReportPerBWP = maxNumberAperiodicCSIReportPerBWP;
	}

	public BerInteger getMaxNumberAperiodicCSIReportPerBWP() {
		return maxNumberAperiodicCSIReportPerBWP;
	}

	public void setMaxNumberSemiPersistentCSIReportPerBWP(BerInteger maxNumberSemiPersistentCSIReportPerBWP) {
		this.maxNumberSemiPersistentCSIReportPerBWP = maxNumberSemiPersistentCSIReportPerBWP;
	}

	public BerInteger getMaxNumberSemiPersistentCSIReportPerBWP() {
		return maxNumberSemiPersistentCSIReportPerBWP;
	}

	public void setSimultaneousCSIReportsAllCC(BerInteger simultaneousCSIReportsAllCC) {
		this.simultaneousCSIReportsAllCC = simultaneousCSIReportsAllCC;
	}

	public BerInteger getSimultaneousCSIReportsAllCC() {
		return simultaneousCSIReportsAllCC;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		codeLength += simultaneousCSIReportsAllCC.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 3
		reverseOS.write(0x83);
		codeLength += 1;
		
		codeLength += maxNumberSemiPersistentCSIReportPerBWP.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 2
		reverseOS.write(0x82);
		codeLength += 1;
		
		codeLength += maxNumberAperiodicCSIReportPerBWP.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 1
		reverseOS.write(0x81);
		codeLength += 1;
		
		codeLength += maxNumberPeriodicCSIReportPerBWP.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 0
		reverseOS.write(0x80);
		codeLength += 1;
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			maxNumberPeriodicCSIReportPerBWP = new BerInteger();
			subCodeLength += maxNumberPeriodicCSIReportPerBWP.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			maxNumberAperiodicCSIReportPerBWP = new BerInteger();
			subCodeLength += maxNumberAperiodicCSIReportPerBWP.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			maxNumberSemiPersistentCSIReportPerBWP = new BerInteger();
			subCodeLength += maxNumberSemiPersistentCSIReportPerBWP.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
			simultaneousCSIReportsAllCC = new BerInteger();
			subCodeLength += simultaneousCSIReportsAllCC.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (maxNumberPeriodicCSIReportPerBWP != null) {
			sb.append("maxNumberPeriodicCSIReportPerBWP: ").append(maxNumberPeriodicCSIReportPerBWP);
		}
		else {
			sb.append("maxNumberPeriodicCSIReportPerBWP: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (maxNumberAperiodicCSIReportPerBWP != null) {
			sb.append("maxNumberAperiodicCSIReportPerBWP: ").append(maxNumberAperiodicCSIReportPerBWP);
		}
		else {
			sb.append("maxNumberAperiodicCSIReportPerBWP: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (maxNumberSemiPersistentCSIReportPerBWP != null) {
			sb.append("maxNumberSemiPersistentCSIReportPerBWP: ").append(maxNumberSemiPersistentCSIReportPerBWP);
		}
		else {
			sb.append("maxNumberSemiPersistentCSIReportPerBWP: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (simultaneousCSIReportsAllCC != null) {
			sb.append("simultaneousCSIReportsAllCC: ").append(simultaneousCSIReportsAllCC);
		}
		else {
			sb.append("simultaneousCSIReportsAllCC: <empty-required-field>");
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

