/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package nr.rrc.definitions;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class MRDCParameters implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private BerEnum singleULTransmission = null;
	private BerEnum dynamicPowerSharing = null;
	private BerEnum tdmPattern = null;
	private BerEnum ulSharingEUTRANR = null;
	private BerEnum ulSwitchingTimeEUTRANR = null;
	private BerEnum simultaneousRxTxInterBandENDC = null;
	private BerEnum asyncIntraBandENDC = null;
	
	public MRDCParameters() {
	}

	public MRDCParameters(byte[] code) {
		this.code = code;
	}

	public void setSingleULTransmission(BerEnum singleULTransmission) {
		this.singleULTransmission = singleULTransmission;
	}

	public BerEnum getSingleULTransmission() {
		return singleULTransmission;
	}

	public void setDynamicPowerSharing(BerEnum dynamicPowerSharing) {
		this.dynamicPowerSharing = dynamicPowerSharing;
	}

	public BerEnum getDynamicPowerSharing() {
		return dynamicPowerSharing;
	}

	public void setTdmPattern(BerEnum tdmPattern) {
		this.tdmPattern = tdmPattern;
	}

	public BerEnum getTdmPattern() {
		return tdmPattern;
	}

	public void setUlSharingEUTRANR(BerEnum ulSharingEUTRANR) {
		this.ulSharingEUTRANR = ulSharingEUTRANR;
	}

	public BerEnum getUlSharingEUTRANR() {
		return ulSharingEUTRANR;
	}

	public void setUlSwitchingTimeEUTRANR(BerEnum ulSwitchingTimeEUTRANR) {
		this.ulSwitchingTimeEUTRANR = ulSwitchingTimeEUTRANR;
	}

	public BerEnum getUlSwitchingTimeEUTRANR() {
		return ulSwitchingTimeEUTRANR;
	}

	public void setSimultaneousRxTxInterBandENDC(BerEnum simultaneousRxTxInterBandENDC) {
		this.simultaneousRxTxInterBandENDC = simultaneousRxTxInterBandENDC;
	}

	public BerEnum getSimultaneousRxTxInterBandENDC() {
		return simultaneousRxTxInterBandENDC;
	}

	public void setAsyncIntraBandENDC(BerEnum asyncIntraBandENDC) {
		this.asyncIntraBandENDC = asyncIntraBandENDC;
	}

	public BerEnum getAsyncIntraBandENDC() {
		return asyncIntraBandENDC;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		if (asyncIntraBandENDC != null) {
			codeLength += asyncIntraBandENDC.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 6
			reverseOS.write(0x86);
			codeLength += 1;
		}
		
		if (simultaneousRxTxInterBandENDC != null) {
			codeLength += simultaneousRxTxInterBandENDC.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 5
			reverseOS.write(0x85);
			codeLength += 1;
		}
		
		if (ulSwitchingTimeEUTRANR != null) {
			codeLength += ulSwitchingTimeEUTRANR.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 4
			reverseOS.write(0x84);
			codeLength += 1;
		}
		
		if (ulSharingEUTRANR != null) {
			codeLength += ulSharingEUTRANR.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 3
			reverseOS.write(0x83);
			codeLength += 1;
		}
		
		if (tdmPattern != null) {
			codeLength += tdmPattern.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 2
			reverseOS.write(0x82);
			codeLength += 1;
		}
		
		if (dynamicPowerSharing != null) {
			codeLength += dynamicPowerSharing.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 1
			reverseOS.write(0x81);
			codeLength += 1;
		}
		
		if (singleULTransmission != null) {
			codeLength += singleULTransmission.encode(reverseOS, false);
			// write tag: CONTEXT_CLASS, PRIMITIVE, 0
			reverseOS.write(0x80);
			codeLength += 1;
		}
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		if (totalLength == 0) {
			return codeLength;
		}
		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			singleULTransmission = new BerEnum();
			subCodeLength += singleULTransmission.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			dynamicPowerSharing = new BerEnum();
			subCodeLength += dynamicPowerSharing.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			tdmPattern = new BerEnum();
			subCodeLength += tdmPattern.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
			ulSharingEUTRANR = new BerEnum();
			subCodeLength += ulSharingEUTRANR.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 4)) {
			ulSwitchingTimeEUTRANR = new BerEnum();
			subCodeLength += ulSwitchingTimeEUTRANR.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 5)) {
			simultaneousRxTxInterBandENDC = new BerEnum();
			subCodeLength += simultaneousRxTxInterBandENDC.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
			subCodeLength += berTag.decode(is);
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 6)) {
			asyncIntraBandENDC = new BerEnum();
			subCodeLength += asyncIntraBandENDC.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		boolean firstSelectedElement = true;
		if (singleULTransmission != null) {
			sb.append("\n");
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("singleULTransmission: ").append(singleULTransmission);
			firstSelectedElement = false;
		}
		
		if (dynamicPowerSharing != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("dynamicPowerSharing: ").append(dynamicPowerSharing);
			firstSelectedElement = false;
		}
		
		if (tdmPattern != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("tdmPattern: ").append(tdmPattern);
			firstSelectedElement = false;
		}
		
		if (ulSharingEUTRANR != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ulSharingEUTRANR: ").append(ulSharingEUTRANR);
			firstSelectedElement = false;
		}
		
		if (ulSwitchingTimeEUTRANR != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("ulSwitchingTimeEUTRANR: ").append(ulSwitchingTimeEUTRANR);
			firstSelectedElement = false;
		}
		
		if (simultaneousRxTxInterBandENDC != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("simultaneousRxTxInterBandENDC: ").append(simultaneousRxTxInterBandENDC);
			firstSelectedElement = false;
		}
		
		if (asyncIntraBandENDC != null) {
			if (!firstSelectedElement) {
				sb.append(",\n");
			}
			for (int i = 0; i < indentLevel + 1; i++) {
				sb.append("\t");
			}
			sb.append("asyncIntraBandENDC: ").append(asyncIntraBandENDC);
			firstSelectedElement = false;
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

