/**
 * This class file was automatically generated by jASN1 v1.10.0 (http://www.openmuc.org)
 */

package nr.rrc.definitions;

import java.io.IOException;
import java.io.EOFException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.io.Serializable;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;


public class TypeIMultiPanelCodebook implements BerType, Serializable {

	private static final long serialVersionUID = 1L;

	public static final BerTag tag = new BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16);

	public byte[] code = null;
	private BerEnum maxNumberTxPortsPerResource = null;
	private BerInteger maxNumberResources = null;
	private BerInteger totalNumberTxPorts = null;
	private BerEnum supportedCodebookMode = null;
	private BerEnum supportedNumberPanels = null;
	private BerInteger maxNumberCSIRSPerResourceSet = null;
	
	public TypeIMultiPanelCodebook() {
	}

	public TypeIMultiPanelCodebook(byte[] code) {
		this.code = code;
	}

	public void setMaxNumberTxPortsPerResource(BerEnum maxNumberTxPortsPerResource) {
		this.maxNumberTxPortsPerResource = maxNumberTxPortsPerResource;
	}

	public BerEnum getMaxNumberTxPortsPerResource() {
		return maxNumberTxPortsPerResource;
	}

	public void setMaxNumberResources(BerInteger maxNumberResources) {
		this.maxNumberResources = maxNumberResources;
	}

	public BerInteger getMaxNumberResources() {
		return maxNumberResources;
	}

	public void setTotalNumberTxPorts(BerInteger totalNumberTxPorts) {
		this.totalNumberTxPorts = totalNumberTxPorts;
	}

	public BerInteger getTotalNumberTxPorts() {
		return totalNumberTxPorts;
	}

	public void setSupportedCodebookMode(BerEnum supportedCodebookMode) {
		this.supportedCodebookMode = supportedCodebookMode;
	}

	public BerEnum getSupportedCodebookMode() {
		return supportedCodebookMode;
	}

	public void setSupportedNumberPanels(BerEnum supportedNumberPanels) {
		this.supportedNumberPanels = supportedNumberPanels;
	}

	public BerEnum getSupportedNumberPanels() {
		return supportedNumberPanels;
	}

	public void setMaxNumberCSIRSPerResourceSet(BerInteger maxNumberCSIRSPerResourceSet) {
		this.maxNumberCSIRSPerResourceSet = maxNumberCSIRSPerResourceSet;
	}

	public BerInteger getMaxNumberCSIRSPerResourceSet() {
		return maxNumberCSIRSPerResourceSet;
	}

	public int encode(OutputStream reverseOS) throws IOException {
		return encode(reverseOS, true);
	}

	public int encode(OutputStream reverseOS, boolean withTag) throws IOException {

		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				reverseOS.write(code[i]);
			}
			if (withTag) {
				return tag.encode(reverseOS) + code.length;
			}
			return code.length;
		}

		int codeLength = 0;
		codeLength += maxNumberCSIRSPerResourceSet.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 5
		reverseOS.write(0x85);
		codeLength += 1;
		
		codeLength += supportedNumberPanels.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 4
		reverseOS.write(0x84);
		codeLength += 1;
		
		codeLength += supportedCodebookMode.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 3
		reverseOS.write(0x83);
		codeLength += 1;
		
		codeLength += totalNumberTxPorts.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 2
		reverseOS.write(0x82);
		codeLength += 1;
		
		codeLength += maxNumberResources.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 1
		reverseOS.write(0x81);
		codeLength += 1;
		
		codeLength += maxNumberTxPortsPerResource.encode(reverseOS, false);
		// write tag: CONTEXT_CLASS, PRIMITIVE, 0
		reverseOS.write(0x80);
		codeLength += 1;
		
		codeLength += BerLength.encodeLength(reverseOS, codeLength);

		if (withTag) {
			codeLength += tag.encode(reverseOS);
		}

		return codeLength;

	}

	public int decode(InputStream is) throws IOException {
		return decode(is, true);
	}

	public int decode(InputStream is, boolean withTag) throws IOException {
		int codeLength = 0;
		int subCodeLength = 0;
		BerTag berTag = new BerTag();

		if (withTag) {
			codeLength += tag.decodeAndCheck(is);
		}

		BerLength length = new BerLength();
		codeLength += length.decode(is);

		int totalLength = length.val;
		codeLength += totalLength;

		subCodeLength += berTag.decode(is);
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
			maxNumberTxPortsPerResource = new BerEnum();
			subCodeLength += maxNumberTxPortsPerResource.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
			maxNumberResources = new BerInteger();
			subCodeLength += maxNumberResources.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
			totalNumberTxPorts = new BerInteger();
			subCodeLength += totalNumberTxPorts.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
			supportedCodebookMode = new BerEnum();
			subCodeLength += supportedCodebookMode.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 4)) {
			supportedNumberPanels = new BerEnum();
			subCodeLength += supportedNumberPanels.decode(is, false);
			subCodeLength += berTag.decode(is);
		}
		else {
			throw new IOException("Tag does not match the mandatory sequence element tag.");
		}
		
		if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 5)) {
			maxNumberCSIRSPerResourceSet = new BerInteger();
			subCodeLength += maxNumberCSIRSPerResourceSet.decode(is, false);
			if (subCodeLength == totalLength) {
				return codeLength;
			}
		}
		throw new IOException("Unexpected end of sequence, length tag: " + totalLength + ", actual sequence length: " + subCodeLength);

		
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		ReverseByteArrayOutputStream reverseOS = new ReverseByteArrayOutputStream(encodingSizeGuess);
		encode(reverseOS, false);
		code = reverseOS.getArray();
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		appendAsString(sb, 0);
		return sb.toString();
	}

	public void appendAsString(StringBuilder sb, int indentLevel) {

		sb.append("{");
		sb.append("\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (maxNumberTxPortsPerResource != null) {
			sb.append("maxNumberTxPortsPerResource: ").append(maxNumberTxPortsPerResource);
		}
		else {
			sb.append("maxNumberTxPortsPerResource: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (maxNumberResources != null) {
			sb.append("maxNumberResources: ").append(maxNumberResources);
		}
		else {
			sb.append("maxNumberResources: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (totalNumberTxPorts != null) {
			sb.append("totalNumberTxPorts: ").append(totalNumberTxPorts);
		}
		else {
			sb.append("totalNumberTxPorts: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (supportedCodebookMode != null) {
			sb.append("supportedCodebookMode: ").append(supportedCodebookMode);
		}
		else {
			sb.append("supportedCodebookMode: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (supportedNumberPanels != null) {
			sb.append("supportedNumberPanels: ").append(supportedNumberPanels);
		}
		else {
			sb.append("supportedNumberPanels: <empty-required-field>");
		}
		
		sb.append(",\n");
		for (int i = 0; i < indentLevel + 1; i++) {
			sb.append("\t");
		}
		if (maxNumberCSIRSPerResourceSet != null) {
			sb.append("maxNumberCSIRSPerResourceSet: ").append(maxNumberCSIRSPerResourceSet);
		}
		else {
			sb.append("maxNumberCSIRSPerResourceSet: <empty-required-field>");
		}
		
		sb.append("\n");
		for (int i = 0; i < indentLevel; i++) {
			sb.append("\t");
		}
		sb.append("}");
	}

}

